name: "My First GitHub Actions"

on: push

env:
  PRESET_VALUE: "This is the value preset"

jobs:
  first_job:
    name: "First Job"
    runs-on: ubuntu-latest

    steps:
      - name: Mask output value
        shell: bash
        run: |
          value1='This is the super secret value'

          echo "::add-mask::$value1"
          echo "::set-output name=first_value::$value1"

      - name: Check output value
        shell: bash
        run: |
          echo "value: ${{ steps.first.outputs.first_value }}"

      - name: Check GitHub Secrets
        shell: bash
        run: |
          echo "secret: ${{ secrets.HELLO }}"
