name: "Manual Release"

on:
  workflow_dispatch:
    inputs:
      title:
        type: string
        required: true
        discription: Title of release
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
 call_build:
    uses: ./.github/workflows.ci.yaml
    with:
      artifact_name: apiapp
      
  call_release:
    uses: ./.github/workflows.cd.yaml
    with:
      title: ${{ github.event.inputs.title }}
      artifact_name: apiapp
    secrets: inherit